/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package herreraederish_p5;

import capalogica.UsuariosDao;
import capalogica.UsuariosLogica;
import javax.swing.JOptionPane;


/**
 *
 * @author Ederi
 */
public class frmUsuario extends javax.swing.JFrame {

     UsuariosLogica usuariosLogica;
     UsuariosDao usuariosDao;
    /**
     * Creates new form frmUsuario
     */
    public frmUsuario() {
        initComponents();
       usuariosLogica = new UsuariosLogica();
       usuariosDao = new UsuariosDao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtClave = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        rdbAdministrador = new javax.swing.JRadioButton();
        rdbUsuario = new javax.swing.JRadioButton();
        rdbAsistente = new javax.swing.JRadioButton();
        btnBuscar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jRadioButton2.setText("usuario");

        jRadioButton4.setText("usuario");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Correo:");

        jLabel2.setText("Clave:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Apellidos:");

        buttonGroup1.add(rdbAdministrador);
        rdbAdministrador.setText("Administrador");

        buttonGroup1.add(rdbUsuario);
        rdbUsuario.setSelected(true);
        rdbUsuario.setText("usuario");

        buttonGroup1.add(rdbAsistente);
        rdbAsistente.setText("Asistente");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rdbUsuario)
                            .addComponent(btnBuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnActualizar)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar)
                                .addGap(23, 23, 23))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdbAsistente)
                                .addGap(18, 18, 18)
                                .addComponent(rdbAdministrador)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(txtCorreo)
                                .addComponent(jLabel2)
                                .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(txtApellido))
                            .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbUsuario)
                    .addComponent(rdbAsistente)
                    .addComponent(rdbAdministrador))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnGuardar)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        String elCorreo = txtCorreo.getText().toString().trim();
        String nombres = txtNombre.getText().toString().trim();
        String apellidos = txtApellido.getText().toString().trim();
        String clave = txtClave.getText().toString().trim();

        int elNivel = -1;
        if (rdbUsuario.isSelected()) {
            elNivel = 1;
        }
        if (rdbAsistente.isSelected()) {
            elNivel = 2;
        } else {
            elNivel = 3;
        }
        usuariosDao.setNombres(nombres);
        usuariosDao.setApellidos(apellidos);
        usuariosDao.setCorreos(elCorreo);
        usuariosDao.setClaves(clave);
        usuariosDao.setNiveles(elNivel);
        
        boolean resultado = usuariosLogica.InsertarUsuario(usuariosDao);
        if (resultado) {
            JOptionPane.showMessageDialog(rootPane, "El correo ya esta registrado ");
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Se Inserto el registro... ");
            
        txtNombre.setText("");
        txtApellido.setText("");
        txtClave.setText("");
        txtCorreo.setText("");
        rdbUsuario.setSelected(true);
        rdbAsistente.setSelected(false);
        rdbAdministrador.setSelected(false);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
       String elCorreo = txtCorreo.getText().toString().trim();
    
    if (elCorreo.isEmpty()) {
        JOptionPane.showMessageDialog(rootPane, "Por favor, ingrese un correo electrónico para eliminar.");
        return;
    }
    usuariosDao.setCorreos(elCorreo);
    
    boolean resultado = usuariosLogica.EliminarUsuario(usuariosDao);
    
    if (resultado) {
         JOptionPane.showMessageDialog(rootPane, "Error al eliminar el usuario.");
        
         
    } else {
       JOptionPane.showMessageDialog(rootPane, "Usuario eliminado correctamente.");
       txtNombre.setText("");
        txtApellido.setText("");
        txtClave.setText("");
        txtCorreo.setText("");
        rdbUsuario.setSelected(false);
        rdbAsistente.setSelected(false);
        rdbAdministrador.setSelected(false);
    }  
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String elCorreo = txtCorreo.getText().toString().trim();
    usuariosDao = usuariosLogica.buscarUsuario(elCorreo);
    
    if (usuariosDao == null) 
    {
        JOptionPane.showMessageDialog(rootPane, "Correo no encontrado");
    } 
    else 
    {   
        txtNombre.setText(usuariosDao.getNombres());
        txtApellido.setText(usuariosDao.getApellidos());
        txtClave.setText(usuariosDao.getClaves());
        switch (usuariosDao.getNiveles()) {
            case 1:
                rdbUsuario.setSelected(true);
                break;
            case 2:
                rdbAsistente.setSelected(true);
                break;
            case 3:
                rdbAdministrador.setSelected(true);
                break;
        }
    }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        String elCorreo = txtCorreo.getText().toString().trim();
    String nombres = txtNombre.getText().toString().trim();
    String apellidos = txtApellido.getText().toString().trim();
    String clave = txtClave.getText().toString().trim();
    
    int elNivel = -1;
    if (rdbUsuario.isSelected()) {
        elNivel = 1;
    } else if (rdbAsistente.isSelected()) {
        elNivel = 2;
    } else {
        elNivel = 3;
    }
    
    // Verificar que el correo no esté vacío
    if (elCorreo.isEmpty()) {
        JOptionPane.showMessageDialog(rootPane, "Por favor, ingrese un correo electrónico.");
        return;
    }
    
    // Establecer los datos en el objeto UsuariosDao
    usuariosDao.setCorreos(elCorreo);
    usuariosDao.setNombres(nombres);
    usuariosDao.setApellidos(apellidos);
    usuariosDao.setClaves(clave);
    usuariosDao.setNiveles(elNivel);
    
    // Llamar al método para actualizar el usuario
    boolean resultado = usuariosLogica.ActualizarUsuario(usuariosDao);
    
    if (resultado) {
        JOptionPane.showMessageDialog(rootPane, "Error al actualizar el usuario.");
        
    } else {
        JOptionPane.showMessageDialog(rootPane, "Usuario actualizado correctamente.");
    }
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JRadioButton rdbAdministrador;
    private javax.swing.JRadioButton rdbAsistente;
    private javax.swing.JRadioButton rdbUsuario;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

}